src/Entity/Video.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\Index as Index;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VideoRepository")
 * @ORM\Table(name="videos", indexes={@Index(name="title_idx", columns={"title"})})
 */
class Video
{
    public const VimeoPath = 'https://player.vimeo.com/video/';
    public const VideoNotLoggedInOrNoMembers = 113716040;
    public const perPage=5;
    public const uploadFolder ="/uploads/videos";
    /**
     * @ORM\Id
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $duration;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $path;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="videos")
     */
    private $category;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="video", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="likedVideos")
     * @ORM\JoinTable(name="likes")
     */
    private $usersThatLike;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="dislikedVideos")
     * @ORM\JoinTable(name="dislikes")
     */
    private $usersThatDontLike;

    /**
     * @Assert\NotBlank(message="Please select a valid file.")
     * @Assert\File(mimeTypes={"video/mp4"})
     */
    private $uploaded_video;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->usersThatLike = new ArrayCollection();
        $this->usersThatDontLike = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(int $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getPath(): ?string
    {
        return $this->path;
    }
    public function getVimeoId(): ?string
    {
        return $this->path;
    }
    public function setPath(string $path): self
    {
        $this->path = $path;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setVideo($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getVideo() === $this) {
                $comment->setVideo(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsersThatLike(): Collection
    {
        return $this->usersThatLike;
    }

    public function addUsersThatLike(User $usersThatLike): self
    {
        if (!$this->usersThatLike->contains($usersThatLike)) {
            $this->usersThatLike[] = $usersThatLike;
        }

        return $this;
    }

    public function removeUsersThatLike(User $usersThatLike): self
    {
        if ($this->usersThatLike->contains($usersThatLike)) {
            $this->usersThatLike->removeElement($usersThatLike);
        }

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsersThatDontLike(): Collection
    {
        return $this->usersThatDontLike;
    }

    public function addUsersThatDontLike(User $usersThatDontLike): self
    {
        if (!$this->usersThatDontLike->contains($usersThatDontLike)) {
            $this->usersThatDontLike[] = $usersThatDontLike;
        }

        return $this;
    }

    public function removeUsersThatDontLike(User $usersThatDontLike): self
    {
        if ($this->usersThatDontLike->contains($usersThatDontLike)) {
            $this->usersThatDontLike->removeElement($usersThatDontLike);
        }

        return $this;
    }

    public function getUploadedVideo()
    {
        return $this->uploaded_video;
    }

    public function setUploadedVideo($uploaded_video): self
    {
        $this->uploaded_video = $uploaded_video;

        return $this;
    }
}

src/Controller/FrontController.php
<?php
/*
|--------------------------------------------------------
| copyright netprogs.pl | available only at Udemy.com | further distribution is prohibited  ***
|--------------------------------------------------------
*/
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Category;
use App\Entity\Video;
use App\Repository\VideoRepository;
use App\Utils\CategoryTreeFrontPage;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Comment;
use App\Controller\Traits\Likes;
use App\Utils\VideoForNoValidSubscription;
class FrontController extends AbstractController
{
    use Likes;
    /**
     * @Route("/", name="main_page")
     */
    public function index()
    {
        return $this->render('front/index.html.twig');
    }

    /**
     * @Route("/video-list/category/{categoryname}/{id}/{page}", defaults={"page": "1"}, name="video_list")
     */
    public function videoList($id, $page, CategoryTreeFrontPage $categories, Request $request, VideoForNoValidSubscription $video_no_members )
    {

        $ids = $categories->getChildIds($id);
        $ids[] = $id;

        $videos = $this->getDoctrine()
        ->getRepository(Video::class)
        ->findByChildIds($ids ,$page, $request->get('sortby'));

        $categories->getCategoryListAndParent($id);
        return $this->render('front/video_list.html.twig',[
            'subcategories' => $categories,
            'videos'=>$videos,
            'video_no_members' => $video_no_members->check()
        ]);
    }

    /**
     * @Route("/video-details/{video}", name="video_details")
     */
    public function videoDetails(VideoRepository $repo, $video, VideoForNoValidSubscription $video_no_members)
    {
        return $this->render('front/video_details.html.twig',
        [
            'video'=>$repo->videoDetails($video),
            'video_no_members' => $video_no_members->check()
        ]);
    }

    /**
     * @Route("/new-comment/{video}", methods={"POST"}, name="new_comment")
    */
    public function newComment(Video $video, Request $request )
     {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_REMEMBERED');
        
        if ( !empty( trim($request->request->get('comment')) ) ) 
        {   

            // $video = $this->getDoctrine()->getRepository(Video::class)->find($video_id);
        
            $comment = new Comment();
            $comment->setContent($request->request->get('comment'));
            $comment->setUser($this->getUser());
            $comment->setVideo($video);

            $em = $this->getDoctrine()->getManager();
            $em->persist($comment);
            $em->flush();
        }
        
        return $this->redirectToRoute('video_details',['video'=>$video->getId()]);
     }

    /**
     * @Route("/search-results/{page}", methods={"GET"}, defaults={"page": "1"}, name="search_results")
     */
    public function searchResults($page, Request $request, VideoForNoValidSubscription $video_no_members)
    {
        $videos = null;
        $query = null;

        if($query = $request->get('query'))
        {
            $videos = $this->getDoctrine()
            ->getRepository(Video::class)
            ->findByTitle($query, $page, $request->get('sortby'));

            if(!$videos->getItems()) $videos = null;
        }
       
        return $this->render('front/search_results.html.twig',[
            'videos' => $videos,
            'query' => $query,
            'video_no_members' => $video_no_members->check()
        ]);
    }




    public function mainCategories()
    {
        $categories = $this->getDoctrine()
        ->getRepository(Category::class)
        ->findBy(['parent'=>null], ['name'=>'ASC']);
        return $this->render('front/_main_categories.html.twig',[
            'categories'=>$categories
        ]);
    }


        /**
     * @Route("/video-list/{video}/like", name="like_video", methods={"POST"})
     * @Route("/video-list/{video}/dislike", name="dislike_video", methods={"POST"})
     * @Route("/video-list/{video}/unlike", name="undo_like_video", methods={"POST"})
     * @Route("/video-list/{video}/undodislike", name="undo_dislike_video", methods={"POST"})
     */
    public function toggleLikesAjax(Video $video, Request $request)
    {
        
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_REMEMBERED');

        switch($request->get('_route'))
        {
            case 'like_video':
            $result = $this->likeVideo($video);
            break;
            
            case 'dislike_video':
            $result = $this->dislikeVideo($video);
            break;

            case 'undo_like_video':
            $result = $this->undoLikeVideo($video);
            break;

            case 'undo_dislike_video':
            $result = $this->undoDislikeVideo($video);
            break;
        }

        return $this->json(['action' => $result,'id'=>$video->getId()]);
    }


}

templates/front/includes/__likes.html.twig
{% if video in app.user.getLikedVideos %}
{% set userLikesVideo = 'userLikesVideo' %}
{% elseif video in app.user.getDislikedVideos %}
{% set userDoesNotLikeVideo = 'userDoesNotLikeVideo' %}
{% else %}
{% set noActionYet = 'noActionYet' %}
{% endif %}

<button data-toggle="tooltip" data-placement="top" title="Click to like the video" type="button" class="btn btn-primary btn-outline-success btn-sm ml-1 video-id-{{video.id}}  click-to-like-video {{noActionYet|default(null)}}">
    <i  href="{{path('like_video',{'video':video.id})}}" class="fa fa-thumbs-up toogle-likes"></i>
</button>

<button data-toggle="tooltip" data-placement="top" title="You like the video. Click to unlike" type="button" class="btn btn-primary btn-outline-success btn-sm mr-2 ml-1 likes-video-id-{{video.id}} click-to-unlike-video {{userLikesVideo|default(null)}}">
    <i href="{{path('undo_like_video',{'video':video.id})}}" class="fa fa-thumbs-up toogle-likes"></i>
</button>

<button data-toggle="tooltip" data-placement="top" title="Click to dislike the video" type="button" class="btn btn-primary btn-outline-danger btn-sm ml-1 mr-1 video-id-{{video.id}}  click-to-dislike-video {{noActionYet|default(null)}}">
    <i href="{{path('dislike_video',{'video':video.id})}}" class="fa fa-thumbs-down toogle-likes"></i>
</button>

<button data-toggle="tooltip" data-placement="top" title="You don't like the video. Click to undo" type="button" class="btn btn-primary btn-outline-danger btn-sm mr-2 ml-1 dislikes-video-id-{{video.id}} click-to-undo-dislike-video {{userDoesNotLikeVideo|default(null)}}">
   <i href="{{path('undo_dislike_video',{'video':video.id})}}" class="fa fa-thumbs-down toogle-likes"></i>
</button>

templates/front/includes/__sort.html.twig
    <form id="form-sorting" action="" method="GET">
        <select name="sortby" class="custom-select mr-sm-2" id="inlineFormCustomSelect" onchange='this.form.submit();'>
            <option selected>Sort...</option>
            <option value="rating">Highest rated</option>
            <option value="ASC">Title A-Z</option>
            <option value="DESC">Title Z-A</option>
        </select>
        {% if query is defined %}
        <input type="hidden" name="query" value="{{ query }}">
        {% endif %}
    </form>

templates/front/includes/__videos.html.twig
<div class="album py-5 bg-light">
        <div class="container">

            <div class="row">
                {% for video in videos %}
                    {% if video_no_members is not null %}
                    {% set videoid = 'https://player.vimeo.com/video/' ~ video_no_members %}
                {% else %}
                    {% set videoid = video.vimeoId %}
                {% endif %}
                    <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <div align="center" class="embed-responsive embed-responsive-16by9">
                            <iframe class="" src="{{ videoid }}" frameborder="0"
                                allowfullscreen></iframe>
                        </div>
                        <div class="card-body">
                            <h3>{{video.getTitle()}}</h3>
                            {% if not app.user or video_no_members is not null %}
                            <p class="card-text text-danger">Video for <b>MEMBERS</b> only. <a href="{{path('pricing')}}">Sign
                                    up</a> for one month for free.</p>
                            {% endif  %}
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">

                                    <i class="fa fa-thumbs-up"><small class="text-muted number-of-likes-{{video.id}}">({{video.usersthatlike.count}})</small></i>&nbsp;
                                    <i class="fa fa-thumbs-down"><small class="text-muted number-of-dislikes-{{video.id}}">({{video.usersthatdontlike.count}})</small></i>
                                    {% if is_granted('IS_AUTHENTICATED_REMEMBERED')  %}
                                    {{ include('front/includes/__likes.html.twig', {'video' : video}) }}
                                    {% endif  %}
                                    <a class="ml-1" href="{{path('video_details',{'video':video.id})}}#video_comments">Comments ({{video.comments.count}})</a>
                                </div>
                                <small class="text-muted">{{video.getDuration()}} mins</small>
                            </div>
                        </div>
                    </div>
                </div>
               {% endfor %}

            </div>
        </div>
    </div>